### ISSUE TITLE
name in input is not working

### ISSUE THREAD

**Issue by oran1248** [serverless-components/schedule#5]
Hi,

I set the name input like this:
```
myLambda:
  component: "@serverless/schedule"
  inputs:
    code:
      src: ./src
    name: my-name
    runtime: nodejs12.x
    rate: 1m
    region: eu-west-1
    memory: 128
    timeout: 30
```

I saw the commit that added name to the inputs list but for some reason it's not working, maybe it's not released yet?
